import { chromium } from '/Users/kevin.parra/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import { writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8765/');
await page.getByRole('heading',{name:'Resumen general',exact:true}).waitFor();
assert((await page.locator('.metric').first().textContent()).includes('143.859'));
await page.screenshot({path:'/tmp/kp-overview.png',fullPage:true});
await page.getByRole('link',{name:'Seguimiento',exact:true}).click();
await page.getByRole('heading',{name:'Seguimiento',exact:true}).waitFor();
assert.equal(await page.locator('.route-panel').count(),2);
assert.equal(await page.locator('.stop-button').count(),12);
assert.equal(await page.locator('.bus-chip').count(),12);
await page.locator('.bus-chip[data-bus="KPA3101"]').click();
assert((await page.locator('#dialog-body').textContent()).includes('Universidad Nacional'));
assert((await page.locator('#dialog-body').textContent()).includes('Parkway'));
await page.getByRole('button',{name:'Cerrar detalle'}).click();
await page.locator('[data-stop="P101"]').first().click();
assert.equal(await page.locator('#dialog-body [data-bus]').count(),4);
await page.getByRole('button',{name:'Cerrar detalle'}).click();
await page.getByLabel('Ruta',{exact:true}).selectOption('KP02');
assert.equal(await page.locator('.bus-chip').count(),6);
await page.getByLabel('Estado',{exact:true}).selectOption('En tránsito');
assert.equal(await page.locator('.bus-chip').count(),1);
await page.getByLabel('Bus',{exact:true}).selectOption('KPB3108');
assert.equal(await page.locator('.bus-chip').count(),0);
assert((await page.locator('main').textContent()).includes('No hay buses'));
await page.getByRole('button',{name:'Restablecer',exact:true}).click();
await page.screenshot({path:'/tmp/kp-monitor.png',fullPage:true});
await page.getByLabel('Hora del registro',{exact:true}).selectOption('16:00');
assert((await page.locator('.title-row').textContent()).includes('16:00'));
await page.getByRole('link',{name:'Finanzas',exact:true}).click();
await page.getByRole('heading',{name:'Finanzas',exact:true}).waitFor();
assert.equal(await page.locator('.finance-metrics .metric').count(),6);
assert.equal(await page.locator('section.panel').nth(1).locator('tbody tr').count(),3);
await page.getByLabel('Desde',{exact:true}).fill('2026-09-01');
await page.getByLabel('Hasta',{exact:true}).fill('2026-09-18');
assert((await page.locator('.finance-metrics').textContent()).includes('575.436.000'));
assert((await page.locator('.finance-metrics').textContent()).includes('535.271.991'));
await page.getByLabel('Ruta',{exact:true}).selectOption('KP01');
assert((await page.locator('.finance-metrics').textContent()).includes('288.976.000'));
await page.getByLabel('Bus',{exact:true}).selectOption('KPA3102');
await page.getByLabel('Desde',{exact:true}).fill('2026-09-18');
assert((await page.locator('.finance-metrics .metric').first().textContent()).includes('$'));
await page.getByLabel('Desde',{exact:true}).fill('2026-09-19');
await page.getByLabel('Hasta',{exact:true}).fill('2026-09-20');
assert((await page.locator('.finance-metrics').textContent()).includes('No disponible'));
await page.getByRole('button',{name:'Todo el período'}).click();
await page.screenshot({path:'/tmp/kp-finance.png',fullPage:true});
await page.getByRole('link',{name:'Alertas y mantenimiento',exact:true}).click();
await page.getByRole('heading',{name:'Alertas y mantenimiento',exact:true}).waitFor();
assert.equal(await page.locator('section.panel').first().locator('tbody tr').count(),12);
assert.equal(await page.locator('section.panel').nth(1).locator('tbody tr').count(),23);
await page.setViewportSize({width:390,height:844});
for(const view of ['resumen','seguimiento','finanzas','alertas']){
 await page.locator(`nav [data-view="${view}"]`).click();
 await page.waitForTimeout(100);
 const size=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,width:innerWidth}));
 assert(size.scroll<=size.width,`${view} overflows ${JSON.stringify(size)}`);
 await page.screenshot({path:`/tmp/kp-mobile-${view}.png`,fullPage:true});
}
assert.deepEqual(errors,[]);
await writeFile('ui-validation.json',JSON.stringify({passed:true,checks:['Navigation across four sections','Financial amounts reconciled in UI','Date route bus and state filters','Empty states and zero revenue reserve day','12 stops and 12 bus markers','Bus and stop details','Historical time selector','Oil and incident counts','390px mobile layout without page overflow','No browser errors'],webmcp:'Native browser context unavailable; not tested'},null,2));
console.log('All UI checks passed');await browser.close();
